import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat, Nunito, Oswald, Anton } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  weight: ['100', '400', '700'], // choose weights you need
  subsets: ['latin'],
  variable: '--font-montserrat',
});

const nunito = Nunito({
  weight: ['200', '400', '900'],
  subsets: ['latin'],
  variable: '--font-nunito',
});

const oswald = Oswald({
  weight: ['300', '400', '700'], // choose the weights you need
  subsets: ['latin'],
  variable: '--font-oswald',
});

const anton = Anton({
  weight: '400', // only available weight
  subsets: ['latin'],
  variable: '--font-anton',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${montserrat.variable} ${nunito.variable} ${oswald.variable} ${anton.variable}`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
